# -*- coding: utf-8 -*-
"""pandas-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qQ9H_sIOsoS5VXIRLxuyPK5BHF-oFpLc
"""

import pandas as ps
tab=ps.read_csv("https://raw.githubusercontent.com/Premalatha-success/Datasets/main/hotel_bookings.csv")

tab.head()

tab.tail(10)

tab.sample

tab.info()

tab.shape

tab.describe()

tab.describe(include="all")

tab.isnull().sum()

#creating,drop,accessing,modifying table with panda

import pandas as pd
import numpy as np

titles=['w','x','y','z']
sap_list=[10,20,30,40]
array=np.array([1,2,3,4])
dict={'w':100,'x':200,'y':300,'z':400}

pd.Series(data=sap_list)

pd.Series(data=sap_list,index=titles)

pd.Series(dict)

sports1=pd.Series([1,2,3,4],index=['cri','foot','base','golf'])
sports1

sports2=pd.Series([10,2,31,4],index=['cri','foot','basket','golf'])
sports2

sports1+sports2   #NAN not a number

df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns = 'Score1 Score2 Score3 Score4 Score5'.split())
df1

df1["Score1"]

df1[["Score1","Score2","Score3"]]

df2={'ID':['101','102','23','43'],'NAME':['JO','KAY','AKA','SAM'],'PROFIT':[70,60,40,20]}
df=pd.DataFrame(df2)
df

df['ID']

df.drop('ID',axis=1)

df

df.drop('NAME',axis=1)

df.drop(1)

